# GitHub Sponsorships — shows "Sponsor" button on the repo page.
# Uncomment any platform you want to enable.

github: Mohamed-Elhawary
custom: ["https://hawary.dev"]
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
